server.port=8081
spring.application.name=foodspot-user
spring.data.mongodb.auto-index-creation=true
spring.mongodb.uri=mongodb+srv://lijil1717_db_user:lijil5610@cluster0.pktzxtu.mongodb.net/Food_Spot?retryWrites=true&w=majority
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.org.springframework.web=DEBUG

# Gmail SMTP Server Setup
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lijil1717@gmail.com
spring.mail.password=igqnuiadcuqcpjtd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Session timeout
server.servlet.session.timeout=900s

# Multipart file upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB